# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.SmallIntegerField(null=True),
        ),
    ]
