# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_list', '0002_auto_20170608_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.SmallIntegerField(),
        ),
    ]
