# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_list', '0005_auto_20170608_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
